Repository PrincetonUniversity/SPECFEMPP, pull requests merged in 2025-06, with the labels that each got.

#901 Updated the capabilities and the compiler table
  docs/index.rst
  docs/sections/getting_started/index.rst
Labels: documentation

#894 Issue 856 - implemented a clean target
  CMakeLists.txt
  benchmarks/src/CMakeLists.txt
  fortran/meshfem2d/setup/CMakeLists.txt
  fortran/meshfem3d/setup/CMakeLists.txt
Labels: configuration

#874 Add tests for partial_derivatives, sources, stress_intregrand, stress, & boundary.
  core/specfem/point/stress.hpp
  include/enumerations/medium.hpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/point/boundary_tests.cpp
  tests/unit-tests/point/partial_derivatives_tests.cpp
  tests/unit-tests/point/source_tests.cpp
  tests/unit-tests/point/stress_integrand_tests.cpp
  tests/unit-tests/point/stress_tests.cpp
Labels: refactor, tests

#920 Issue 905 - add is_close() utility and apply to point tests
  include/utilities/simd.hpp
  tests/unit-tests/point/boundary_tests.cpp
  tests/unit-tests/point/kernels/dim2/acoustic_isotropic.cpp
  tests/unit-tests/point/kernels/dim2/elastic_anisotropic.cpp
  tests/unit-tests/point/kernels/dim2/elastic_isotropic.cpp
  tests/unit-tests/point/kernels/dim2/poroelastic_isotropic.cpp
  tests/unit-tests/point/kernels/dim3/elastic_isotropic.cpp
  tests/unit-tests/point/partial_derivatives_tests.cpp
  tests/unit-tests/point/properties/dim2/acoustic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/elastic_anisotropic.cpp
  tests/unit-tests/point/properties/dim2/elastic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/electromagnetic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/poroelastic_isotropic.cpp
  tests/unit-tests/point/properties/dim3/elastic_isotropic.cpp
  tests/unit-tests/point/stress_integrand_tests.cpp
  tests/unit-tests/point/stress_tests.cpp
Labels: enhancement, refactor

#915 Update Kokkos version to 4.6.1
  CMakeLists.txt
  core/specfem/point/partial_derivatives.hpp
  include/boundary_conditions/dirichlet/dirichlet.hpp
  include/compute/fields/data_access.tpp
  include/datatypes/simd.hpp
  include/execution/for_each_level.hpp
  include/kokkos_abstractions.h
  include/kokkos_kernels/impl/divide_mass_matrix.tpp
  include/kokkos_kernels/impl/invert_mass_matrix.tpp
  include/medium/dim2/elastic/isotropic/wavefield.hpp
  include/timescheme/newmark.tpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/assembly/properties/properties.cpp
  tests/unit-tests/datatypes/simd_tests.cpp
  tests/unit-tests/point/kernels/dim2/acoustic_isotropic.cpp
  tests/unit-tests/point/kernels/dim2/elastic_anisotropic.cpp
  tests/unit-tests/point/kernels/dim2/elastic_isotropic.cpp
  tests/unit-tests/point/kernels/dim3/elastic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/acoustic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/elastic_anisotropic.cpp
  tests/unit-tests/point/properties/dim2/elastic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/electromagnetic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/poroelastic_isotropic.cpp
Labels: maintenance

#914 Issue 868 -- Made elastic isotropic point properties and kernels dimension templated.
  core/specfem/point/kernels.hpp
  core/specfem/point/properties.hpp
  docs/sections/api/specfem/point/kernels/dim2/elastic_isotropic.rst
  docs/sections/api/specfem/point/kernels/dim3/elastic_isotropic.rst
  docs/sections/api/specfem/point/kernels/index.rst
  include/medium/dim2/elastic/isotropic/material.hpp
  include/medium/dim2/elastic/isotropic/properties_container.hpp
  tests/unit-tests/mesh/materials/properties.cpp
  tests/unit-tests/point/properties/dim2/elastic_isotropic.cpp
  tests/unit-tests/test_macros.hpp
Labels: refactor

#910 Remove NVCC compiler warnings
  CMakeLists.txt
  core/specfem/point/impl/point_container.hpp
  core/specfem/point/kernels.hpp
  core/specfem/point/partial_derivatives.hpp
  core/specfem/point/partial_derivatives.tpp
  include/compute/boundaries/impl/stacey.hpp
  include/compute/compute_partial_derivatives.hpp
  include/compute/fields/data_access.tpp
  include/compute/fields/impl/field_impl.tpp
  include/execution/chunked_domain_iterator.hpp
  include/execution/for_all.hpp
  include/execution/for_each_level.hpp
  include/execution/mapped_chunked_domain_iterator.hpp
  include/execution/policy.hpp
  include/execution/range_iterator.hpp
  include/execution/void_iterator.hpp
  include/io/impl/medium_writer.tpp
  include/kokkos_kernels/impl/compute_mass_matrix.tpp
  include/kokkos_kernels/impl/compute_seismogram.tpp
  include/kokkos_kernels/impl/compute_source_interaction.tpp
  include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
  include/kokkos_kernels/impl/divide_mass_matrix.tpp
  include/kokkos_kernels/impl/invert_mass_matrix.tpp
  include/medium/dim2/elastic/isotropic_cosserat/stress.hpp
  include/medium/dim2/elastic/isotropic_cosserat/wavefield.hpp
  src/compute/assembly/helper.hpp
  src/compute/compute_mesh.cpp
  src/compute/compute_partial_derivatives.cpp
  src/io/mesh/impl/fortran/dim2/read_material_properties.cpp
  src/io/mesh/impl/fortran/dim3/mesh.cpp
  src/io/mesh/impl/fortran/dim3/read_parameters.cpp
  src/mesh/dim3/materials/materials.cpp
  src/mesh/dim3/partial_derivatives/partial_derivatives.cpp
  tests/unit-tests/assembly/properties/properties.cpp
  tests/unit-tests/datatypes/simd_tests.cpp
  tests/unit-tests/point/coordinates_tests.cpp
  tests/unit-tests/point/kernels/dim3/elastic_isotropic.cpp
  tests/unit-tests/policies/policies.cpp
Labels: fix

#930 Add documentation on macros.
  docs/sections/api/index.rst
  docs/sections/api/macros/config_strings.rst
  docs/sections/api/macros/data_container.rst
  docs/sections/api/macros/for_each_in_product.rst
  docs/sections/api/macros/index.rst
  docs/sections/api/macros/point_container.rst
Labels: documentation
