Repository PrincetonUniversity/SPECFEMPP, pull requests merged in 2025-07, with the labels that each got.

#944 Added unit tests for stress computation
  core/specfem/point/stress.hpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/stress/dim2/acoustic.cpp
  tests/unit-tests/stress/dim2/elastic_anisotropic.cpp
  tests/unit-tests/stress/dim2/elastic_isotropic.cpp
  tests/unit-tests/stress/dim2/elastic_isotropic_cosserat.cpp
  tests/unit-tests/stress/dim2/poroelastic_isotropic.cpp
Labels: tests

#972 Adds dim2 template specialization for boundaries
  core/specfem/assembly/assembly.hpp
  core/specfem/assembly/boundaries.cpp
  core/specfem/assembly/boundaries.hpp
  core/specfem/assembly/boundaries/boundary_container.hpp
  core/specfem/assembly/boundaries/boundary_container.tpp
  core/specfem/assembly/boundaries/dim2/boundaries.hpp
  core/specfem/assembly/boundaries/dim2/boundaries.tpp
  core/specfem/assembly/boundaries/dim2/impl/acoustic_free_surface.hpp
  core/specfem/assembly/boundaries/dim2/impl/acoustic_free_surface.tpp
  core/specfem/assembly/boundaries/dim2/impl/stacey.hpp
  core/specfem/assembly/boundaries/dim2/impl/stacey.tpp
  core/specfem/assembly/boundaries/dim2/impl/utilities.hpp
  core/specfem/assembly/boundary_values.cpp
  core/specfem/assembly/boundary_values.hpp
  core/specfem/assembly/boundary_values/boundary_medium_container.hpp
  core/specfem/assembly/boundary_values/boundary_medium_container.tpp
  core/specfem/assembly/boundary_values/boundary_values_container.hpp
  core/specfem/assembly/boundary_values/boundary_values_container.tpp
Labels: refactor

#991 Adds 2D specialization for boundary values - take 2
  core/specfem/assembly/assembly.hpp
  core/specfem/assembly/boundary_values.cpp
  core/specfem/assembly/boundary_values.hpp
  core/specfem/assembly/boundary_values/boundary_values.hpp
  core/specfem/assembly/boundary_values/boundary_values.tpp
  core/specfem/assembly/boundary_values/boundary_values_container.hpp
  core/specfem/assembly/boundary_values/boundary_values_container.tpp
  core/specfem/assembly/boundary_values/dim2/impl/boundary_medium_container.hpp
  core/specfem/assembly/boundary_values/dim2/impl/boundary_medium_container.tpp
  core/specfem/assembly/boundary_values/dim2/impl/boundary_value_container.hpp
  core/specfem/assembly/boundary_values/dim2/impl/boundary_value_container.tpp
  include/io/wavefield/reader.tpp
  include/io/wavefield/writer.tpp
Labels: refactor

#994 Updated fortran mesher to write control nodes
  CMakeLists.txt
  fortran/meshfem3d/generate_databases/save_arrays_solver.F90
  fortran/meshfem3d/generate_databases/save_parameters.f90
  include/io/mesh/impl/fortran/dim3/interface.hpp
  include/io/mesh/impl/fortran/dim3/interface.tpp
  include/io/mesh/impl/fortran/dim3/utilities.hpp
  include/mesh/dim3/control_nodes/control_nodes.hpp
  include/mesh/dim3/mapping/mapping.hpp
  include/mesh/dim3/mesh.hpp
  include/mesh/dim3/parameters/parameters.hpp
  src/io/mesh/impl/fortran/dim3/mesh.cpp
  src/io/mesh/impl/fortran/dim3/read_parameters.cpp
  src/mesh/dim3/control_nodes/control_nodes.cpp
  src/mesh/dim3/mesh.cpp
  src/specfem3d.cpp
Labels: enhancement

#979 Issue 965 + 966 - Template jacobian_matrix and element_types with dimension.
  core/specfem/assembly/assembly.hpp
  core/specfem/assembly/boundaries/dim2/boundaries.hpp
  core/specfem/assembly/boundaries/dim2/boundaries.tpp
  core/specfem/assembly/boundaries/dim2/impl/stacey.hpp
  core/specfem/assembly/boundaries/dim2/impl/stacey.tpp
  core/specfem/assembly/boundary_values/boundary_values.hpp
  core/specfem/assembly/boundary_values/boundary_values.tpp
  core/specfem/assembly/boundary_values/dim2/impl/boundary_medium_container.hpp
  core/specfem/assembly/boundary_values/dim2/impl/boundary_medium_container.tpp
  core/specfem/assembly/boundary_values/dim2/impl/boundary_value_container.hpp
  core/specfem/assembly/boundary_values/dim2/impl/boundary_value_container.tpp
  core/specfem/assembly/coupled_interfaces/dim2/coupled_interfaces.cpp
  core/specfem/assembly/coupled_interfaces/dim2/coupled_interfaces.hpp
  core/specfem/assembly/coupled_interfaces/dim2/impl/interface_container.hpp
  core/specfem/assembly/coupled_interfaces/dim2/impl/interface_container.tpp
  core/specfem/assembly/element_types.hpp
  core/specfem/assembly/element_types/dim2/element_types.cpp
  core/specfem/assembly/element_types/dim2/element_types.hpp
  core/specfem/assembly/fields/dim2/simulation_field.hpp
  core/specfem/assembly/fields/dim2/simulation_field.tpp
  core/specfem/assembly/fields/fields.hpp
  core/specfem/assembly/fields/fields.tpp
  core/specfem/assembly/fields/impl/field_impl.hpp
  core/specfem/assembly/fields/impl/field_impl.tpp
  core/specfem/assembly/jacobian_matrix.hpp
  core/specfem/assembly/jacobian_matrix/dim2/jacobian_matrix.cpp
  core/specfem/assembly/jacobian_matrix/dim2/jacobian_matrix.hpp
  core/specfem/assembly/kernels/dim2/kernels.cpp
  core/specfem/assembly/kernels/dim2/kernels.hpp
  core/specfem/assembly/properties/dim2/properties.cpp
  core/specfem/assembly/properties/dim2/properties.hpp
  core/specfem/assembly/receivers/dim2/receivers.cpp
  core/specfem/assembly/receivers/dim2/receivers.hpp
  core/specfem/assembly/sources/dim2/sources.cpp
  core/specfem/assembly/sources/dim2/sources.hpp
  core/specfem/assembly/sources/impl/source_medium.hpp
  core/specfem/assembly/sources/impl/source_medium.tpp
  include/algorithms/divergence.hpp
  include/algorithms/gradient.hpp
  include/io/impl/medium_writer.hpp
  include/io/impl/medium_writer.tpp
  include/source/adjoint_source.hpp
  include/source/cosserat_force_source.hpp
  include/source/external.hpp
  include/source/force_source.hpp
  include/source/moment_tensor_source.hpp
  include/source/source.hpp
  src/source/adjoint_source.cpp
  src/source/cosserat_force_source.cpp
  src/source/external.cpp
  src/source/force_source.cpp
  src/source/moment_tensor_source.cpp
  tests/unit-tests/assembly_mesh/jacobian_matrix/compute_jacobian_matrix_tests.cpp
  tests/unit-tests/domain/acoustic/rmass_inverse_tests.cpp
  tests/unit-tests/domain/elastic/rmass_inverse_tests.cpp
  tests/unit-tests/source/source_location_tests.cpp
Labels: refactor

#989 Feature unity build test patch
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/MPI_environment.hpp
  tests/unit-tests/assembly/kernels/kernels.cpp
  tests/unit-tests/assembly/properties/properties.cpp
  tests/unit-tests/mass_matrix/dim2/acoustic.cpp
  tests/unit-tests/mass_matrix/dim2/elastic_anisotropic.cpp
  tests/unit-tests/mass_matrix/dim2/elastic_isotropic.cpp
  tests/unit-tests/mass_matrix/dim2/poroelastic.cpp
  tests/unit-tests/mesh/materials/materials.cpp
  tests/unit-tests/mesh/materials/properties.cpp
  tests/unit-tests/stress/dim2/acoustic.cpp
  tests/unit-tests/stress/dim2/elastic_anisotropic.cpp
  tests/unit-tests/stress/dim2/elastic_isotropic.cpp
  tests/unit-tests/stress/dim2/elastic_isotropic_cosserat.cpp
  tests/unit-tests/stress/dim2/poroelastic_isotropic.cpp
Labels: ignore-for-release

#1001 Adds control nodes and points to assembly::mesh
  CMakeLists.txt
  core/specfem/CMakeLists.txt
  core/specfem/assembly/CMakeLists.txt
  core/specfem/assembly/mesh.cpp
  core/specfem/assembly/mesh.hpp
  core/specfem/assembly/mesh/dim2/impl/shape_functions.tpp
  core/specfem/assembly/mesh/dim2/mesh.hpp
  core/specfem/assembly/mesh/dim2/mesh.tpp
  core/specfem/assembly/mesh/dim3/impl/control_nodes.hpp
  core/specfem/assembly/mesh/dim3/impl/control_nodes.tpp
  core/specfem/assembly/mesh/dim3/impl/points.hpp
  core/specfem/assembly/mesh/dim3/impl/points.tpp
  core/specfem/assembly/mesh/dim3/mesh.hpp
  core/specfem/assembly/mesh/dim3/mesh.tpp
  core/specfem/assembly/mesh/impl/quadrature.hpp
  core/specfem/shape_functions.hpp
  core/specfem/shape_functions/CMakeLists.txt
  core/specfem/shape_functions/shape_function_derivatives2d.cpp
  core/specfem/shape_functions/shape_functions.hpp
  core/specfem/shape_functions/shape_functions2d.cpp
  include/jacobian/interface.hpp
  include/jacobian/shape_functions.hpp
  src/jacobian/jacobian.cpp
  src/jacobian/shape_functions.cpp
  tests/unit-tests/jacobian/shape_functions.cpp
Labels: ignore-for-release

#1004 Implements stacey boundaries for Cosserat media
  docs/index.rst
  include/boundary_conditions/stacey/stacey.tpp
  include/enumerations/material_definitions.hpp
Labels: new physics

#1021 3D implementation for Jacobian Matrix
  core/specfem/assembly/fields/data_access.hpp
  core/specfem/assembly/fields/dim2/data_access.hpp
  core/specfem/assembly/jacobian_matrix.hpp
  core/specfem/assembly/jacobian_matrix/dim2/jacobian_matrix.hpp
  core/specfem/assembly/jacobian_matrix/dim3/jacobian_matrix.cpp
  core/specfem/assembly/jacobian_matrix/dim3/jacobian_matrix.hpp
  core/specfem/assembly/jacobian_matrix/dim3/load_on_device.hpp
  core/specfem/assembly/jacobian_matrix/dim3/load_on_host.hpp
  core/specfem/assembly/jacobian_matrix/dim3/store_on_host.hpp
  core/specfem/assembly/sources/dim2/sources.hpp
  core/specfem/data_access.hpp
  core/specfem/data_access/accessor.hpp
  core/specfem/data_access/check_compatibility.hpp
  core/specfem/data_access/container.hpp
  core/specfem/data_access/data_class.hpp
  core/specfem/point/boundary.hpp
  core/specfem/point/field.hpp
  core/specfem/point/field_derivatives.hpp
  core/specfem/point/impl/point_container.hpp
  core/specfem/point/index.hpp
  core/specfem/point/jacobian_matrix.hpp
  core/specfem/point/mapped_index.hpp
  core/specfem/point/source.hpp
  core/specfem/point/stress.hpp
  core/specfem/point/stress_integrand.hpp
  include/boundary_conditions/boundary_conditions.hpp
  include/chunk_element/index.hpp
  include/chunk_element/mapped_index.hpp
  include/coupled_interface/impl/compute_coupling.hpp
  include/enumerations/accessor.hpp
  include/enumerations/container.hpp
  include/enumerations/interface.hpp
  include/io/mesh/impl/fortran/dim3/interface.tpp
  include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
  include/medium/compute_cosserat_couple_stress.hpp
  include/medium/compute_cosserat_stress.hpp
  include/medium/compute_damping_force.hpp
  include/medium/compute_frechet_derivatives.hpp
  include/medium/compute_source.hpp
  include/medium/compute_stress.hpp
  include/medium/dim2/acoustic/isotropic/frechet_derivative.hpp
  include/mesh/dim3/coordinates/coordinates.hpp
  include/mesh/dim3/jacobian_matrix/jacobian_matrix.hpp
  include/mesh/dim3/mapping/mapping.hpp
  include/mesh/dim3/materials/materials.hpp
  src/mesh/dim3/jacobian_matrix/jacobian_matrix.cpp
  tests/unit-tests/point/source_tests.cpp
  tests/unit-tests/point/stress_integrand_tests.cpp
  tests/unit-tests/point/stress_tests.cpp
Labels: enhancement

#1025 Issue 990 Part 2 - Update the way we compute the source vector and tensor
  core/specfem/assembly/compute_source_array/dim2/impl/adjoint_source_array.cpp
  core/specfem/assembly/compute_source_array/dim2/impl/cosserat_force_source_array.cpp
  core/specfem/assembly/compute_source_array/dim2/impl/external_source_array.cpp
  core/specfem/assembly/compute_source_array/dim2/impl/force_source_array.cpp
  core/specfem/assembly/compute_source_array/dim2/impl/moment_tensor_source_array.cpp
  include/enumerations/interface.hpp
  include/source/adjoint_source.hpp
  include/source/cosserat_force_source.hpp
  include/source/external.hpp
  include/source/force_source.hpp
  include/source/moment_tensor_source.hpp
  src/source/adjoint_source.cpp
  src/source/cosserat_force_source.cpp
  src/source/external.cpp
  src/source/force_source.cpp
  src/source/moment_tensor_source.cpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/source/location/serial/source_locations.yml
  tests/unit-tests/source/location/serial/sources.yml
  tests/unit-tests/source/location/source_location_tests.cpp
  tests/unit-tests/source/location/test_config.yml
  tests/unit-tests/source/source.cpp
  tests/unit-tests/source/tensor_sources/moment_tensor_source.cpp
  tests/unit-tests/source/vector_sources/adjoint_source.cpp
  tests/unit-tests/source/vector_sources/cosserat_force_source.cpp
  tests/unit-tests/source/vector_sources/external_source.cpp
  tests/unit-tests/source/vector_sources/force_source.cpp
Labels: refactor

#1059 Fix ASCII Reader/Writer
  include/io/ASCII/impl/datasetbase.hpp
  include/io/ASCII/impl/native_type.tpp
Labels: fix

#1055 Fixed simulation field compilation
  .github/workflows/compilation.yml
  .github/workflows/unittests.yml
  core/specfem/assembly/fields/dim2/simulation_field.cpp
  core/specfem/assembly/fields/dim2/simulation_field.tpp
  core/specfem/assembly/fields/dim3/simulation_field.cpp
  core/specfem/assembly/fields/dim3/simulation_field.tpp
Labels: fix
