Repository PrincetonUniversity/SPECFEMPP, pull requests merged in 2025-08, with the labels that each got.

#1044 Adjacency2d features
  .gitignore
  CMakeLists.txt
  core/specfem/assembly/assembly/dim2/assembly.cpp
  core/specfem/assembly/mesh/dim2/mesh.hpp
  core/specfem/assembly/mesh/dim2/mesh.tpp
  fortran/meshfem2d/CMakeLists.txt
  fortran/meshfem2d/decompose_mesh.F90
  fortran/meshfem2d/read_parameter_file.F90
  fortran/meshfem2d/save_databases.f90
  fortran/meshfem2d/save_databases_adj.f90
  fortran/meshfem2d/shared_par.f90
  include/io/mesh/impl/fortran/dim2/read_adjacency_map.hpp
  include/mesh/dim2/adjacency_map/adjacency_map.hpp
  include/mesh/dim2/mesh.hpp
  src/io/mesh/impl/fortran/dim2/mesh.cpp
  src/io/mesh/impl/fortran/dim2/read_adjacency_map.cpp
  src/mesh/dim2/adjacency_map/adjacency_map.cpp
  src/mesh/dim2/adjacency_map/index_mapping_from_adjacencies.cpp
  src/mesh/dim2/adjacency_map/relative_node_inds.cpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/algorithms/interpolate_function.cpp
  tests/unit-tests/assembly_mesh/index/compute_tests.cpp
  tests/unit-tests/assembly_mesh/jacobian_matrix/compute_jacobian_matrix_tests.cpp
  tests/unit-tests/mortar/adjacency_map/adjtest_2d.cpp
  tests/unit-tests/mortar/fixture/mortar_fixtures.cpp
  tests/unit-tests/mortar/fixture/mortar_fixtures.hpp
  tests/unit-tests/mortar/runner.cpp
  tests/unit-tests/mortar/test_config.yaml
Labels: enhancement, new physics

#1085 Specfem prefix
  .jenkins/gnu_compiler_checks.gvy
  .jenkins/intel_compiler_checks.gvy
  .jenkins/nvidia_compiler_checks.gvy
  .jenkins/unittests.gvy
  CMakeLists.txt
  CMakePresets.json
  benchmarks/src/CMakeLists.txt
  benchmarks/src/dim2/Tromp_2005/CMakeLists.txt
  benchmarks/src/dim2/anisotropic-crystal/CMakeLists.txt
  benchmarks/src/dim2/fluid-solid-bathymetry/CMakeLists.txt
  benchmarks/src/dim2/fluid-solid-interface/CMakeLists.txt
  benchmarks/src/dim2/homogeneous-cosserat/CMakeLists.txt
  benchmarks/src/dim2/homogeneous-medium-flat-topography/CMakeLists.txt
  benchmarks/src/dim2/poroelastic-semi-infinite/CMakeLists.txt
  benchmarks/src/dim2/solid-solid-interface/CMakeLists.txt
  benchmarks/src/dim3/homogeneous_halfspace/CMakeLists.txt
  cmake/vtk.cmake
  core/specfem/assembly/CMakeLists.txt
  docs/sections/getting_started/index.rst
  fortran/meshfem2d/CMakeLists.txt
  fortran/meshfem3d/CMakeLists.txt
  include/datatypes/simd.hpp
  include/macros.hpp
  tests/unit-tests/datatypes/simd_tests.cpp
Labels: configuration

#1098 Issue 1057 - Implements locate_point for 3D
  CMakeLists.txt
  core/specfem/assembly/mesh/dim2/impl/points.hpp
  core/specfem/assembly/mesh/dim2/impl/utilities.hpp
  core/specfem/assembly/mesh/dim2/impl/utilities.tpp
  core/specfem/assembly/mesh/dim2/mesh.tpp
  core/specfem/assembly/sources/impl/locate_sources.tpp
  core/specfem/point/impl/point_container.hpp
  core/specfem/source/dim2/tensor_source/moment_tensor_source.cpp
  core/specfem/source/dim2/vector_source/cosserat_force_source.cpp
  core/specfem/source/dim2/vector_source/force_source.cpp
  core/specfem/source/dim3/tensor_source/moment_tensor_source.cpp
  core/specfem/source/dim3/vector_source/force_source.cpp
  fortran/meshfem3d/generate_databases/CMakeLists.txt
  include/algorithms/locate_point.hpp
  include/algorithms/locate_point_impl.hpp
  include/kokkos_abstractions.h
  include/utilities/simd.hpp
  include/utilities/utilities.hpp
  src/algorithms/dim2/locate_point.cpp
  src/algorithms/dim2/locate_point_impl.cpp
  src/algorithms/dim3/locate_point.cpp
  src/algorithms/dim3/locate_point_impl.cpp
  src/source_time_function/dgaussian.cpp
  src/source_time_function/dirac.cpp
  src/source_time_function/ricker.cpp
  src/utilities/utilities.cpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/algorithms/dim2/locate_point_impl.cpp
  tests/unit-tests/algorithms/dim3/locate_point_impl.cpp
  tests/unit-tests/algorithms/interpolate_function.cpp
  tests/unit-tests/assembly/mesh/utilities.cpp
  tests/unit-tests/assembly/sources/locate_sources.cpp
  tests/unit-tests/assembly/test_config.yaml
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/database.bin
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/provenance/Par_File
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/provenance/README.md
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/provenance/Snakefile
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/provenance/geometry.png
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/provenance/seismograms.png
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/provenance/source.yaml
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/provenance/specfem_config.yaml
  tests/unit-tests/data/mesh/cosserat_isotropic_homogeneous/provenance/topography.dat
  tests/unit-tests/mesh/materials/materials.cpp
  tests/unit-tests/mesh/materials/properties.cpp
  tests/unit-tests/point/boundary_tests.cpp
  tests/unit-tests/point/jacobian_matrix_tests.cpp
  tests/unit-tests/point/kernels/dim2/acoustic_isotropic.cpp
  tests/unit-tests/point/kernels/dim2/elastic_anisotropic.cpp
  tests/unit-tests/point/kernels/dim2/elastic_isotropic.cpp
  tests/unit-tests/point/kernels/dim2/poroelastic_isotropic.cpp
  tests/unit-tests/point/kernels/dim3/elastic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/acoustic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/elastic_anisotropic.cpp
  tests/unit-tests/point/properties/dim2/elastic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/electromagnetic_isotropic.cpp
  tests/unit-tests/point/properties/dim2/poroelastic_isotropic.cpp
  tests/unit-tests/point/properties/dim3/elastic_isotropic.cpp
  tests/unit-tests/point/stress_integrand_tests.cpp
  tests/unit-tests/point/stress_tests.cpp
  tests/unit-tests/utilities/is_close_tests.cpp
Labels: enhancement

#1108 Documentation and deprecate old implementation
  core/specfem/assembly/fields/data_access.hpp
  core/specfem/assembly/fields/dim2/add_on_device.hpp
  core/specfem/assembly/fields/dim2/atomic_add_on_device.hpp
  core/specfem/assembly/fields/dim2/data_access.hpp
  core/specfem/assembly/fields/dim2/impl/atomic_add_access_functions.hpp
  core/specfem/assembly/fields/dim2/impl/load_access_functions.hpp
  core/specfem/assembly/fields/dim2/impl/store_access_functions.hpp
  core/specfem/assembly/fields/dim2/load_on_device.hpp
  core/specfem/assembly/fields/dim2/store_on_device.hpp
  core/specfem/assembly/fields/dim2/store_on_host.hpp
  core/specfem/assembly/fields/impl/add_access_functions.hpp
  core/specfem/assembly/fields/impl/atomic_add_access_functions.hpp
  core/specfem/assembly/fields/impl/field_impl.hpp
  core/specfem/assembly/fields/impl/field_impl.tpp
  core/specfem/assembly/fields/impl/load_access_functions.hpp
  core/specfem/assembly/fields/impl/store_access_functions.hpp
  core/specfem/chunk_element/acceleration.hpp
  core/specfem/chunk_element/displacement.hpp
  core/specfem/chunk_element/impl/field.hpp
  core/specfem/chunk_element/index.hpp
  core/specfem/chunk_element/velocity.hpp
  core/specfem/data_access/check_compatibility.hpp
  core/specfem/data_access/data_class.hpp
  core/specfem/point/acceleration.hpp
  core/specfem/point/displacement.hpp
  core/specfem/point/impl/field.hpp
  core/specfem/point/mass_inverse.hpp
  core/specfem/point/velocity.hpp
  docs/sections/api/datatypes/field/chunk_element.rst
  docs/sections/api/datatypes/field/index.rst
  docs/sections/api/datatypes/index.rst
  docs/sections/api/datatypes/stress_integrands/chunk_element.rst
  docs/sections/api/datatypes/stress_integrands/index.rst
  docs/sections/api/index.rst
  docs/sections/api/specfem/chunk_element/field/acceleration.rst
  docs/sections/api/specfem/chunk_element/field/displacement.rst
  docs/sections/api/specfem/chunk_element/field/velocity.rst
  docs/sections/api/specfem/chunk_element/index.rst
  docs/sections/api/specfem/chunk_element/index/index.rst
  docs/sections/api/specfem/chunk_element/stress_integrand/index.rst
  docs/sections/api/specfem/point/field/acceleration.rst
  docs/sections/api/specfem/point/field/displacement.rst
  docs/sections/api/specfem/point/field/index.rst
  docs/sections/api/specfem/point/field/mass_inverse.rst
  docs/sections/api/specfem/point/field/velocity.rst
  docs/sections/api/specfem/point/index.rst
  include/boundary_conditions/boundary_conditions.hpp
  include/coupled_interface/impl/compute_coupling.hpp
  include/medium/compute_cosserat_couple_stress.hpp
  include/medium/compute_cosserat_stress.hpp
  include/medium/compute_damping_force.hpp
  include/medium/compute_frechet_derivatives.hpp
  include/medium/dim2/acoustic/isotropic/wavefield.hpp
  include/medium/dim2/elastic/anisotropic/wavefield.hpp
  include/medium/dim2/elastic/isotropic/wavefield.hpp
  include/medium/dim2/elastic/isotropic_cosserat/wavefield.hpp
  include/medium/dim2/poroelastic/isotropic/wavefield.hpp
Labels: ignore-for-release

#1143 Issue 1120 - Added 3d elastic isotropic stress and associated unit-tests
  include/medium/compute_stress.hpp
  include/medium/dim3/elastic/isotropic/stress.hpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/stress/dim3/elastic_isotropic.cpp
Labels: new physics

#1119 Interpolate function for 3D
  core/specfem/point/jacobian_matrix.hpp
  include/algorithms/interpolate.hpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/algorithms/interpolate_function.cpp
  tests/unit-tests/algorithms/interpolate_function/dim2/interpolate_function.cpp
  tests/unit-tests/algorithms/interpolate_function/dim3/interpolate_function.cpp
  tests/unit-tests/algorithms/interpolate_function/runner.cpp
Labels: enhancement

#1148 gmsh: topography file to external mesh files
  .gitignore
  scripts/gmshlayerbuilder/README.md
  scripts/gmshlayerbuilder/__main__.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/__init__.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/binary_detect_N3.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/exporter.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/__init__.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/boundary.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/edges.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/index_mapping.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/model.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/nonconforming_interfaces.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/plotter.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/gmsh_dep.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/lagrange.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/topo_import/__init__.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/topo_import/layer_builder/layer.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/topo_import/layer_builder/layer_boundaries.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/topo_import/layer_builder/layeredbuilder.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/topo_import/topo_reader.py
  scripts/gmshlayerbuilder/test_topo.dat
Labels: enhancement
