Repository PrincetonUniversity/SPECFEMPP, pull requests merged in 2025-09, with the labels that each got.

#1145 Issue 1130 - Updated the jacobian tests
  tests/unit-tests/jacobian/dim2/compute_jacobian_tests.cpp
  tests/unit-tests/jacobian/dim2/compute_locations_tests.cpp
  tests/unit-tests/jacobian/dim3/compute_jacobian_tests.cpp
  tests/unit-tests/jacobian/dim3/compute_locations_tests.cpp
Labels: ignore-for-release

#1146 Issue 945 - Updates the STF and force implementations to match SPECFEM2D Fortran
  core/specfem/source/dim2/vector_source/force_source.cpp
  include/medium/dim2/acoustic/isotropic/source.hpp
  include/source_time_function/ricker.hpp
  src/source_time_function/dgaussian.cpp
  src/source_time_function/dirac.cpp
  src/source_time_function/ricker.cpp
  tests/unit-tests/displacement_tests/Newmark/serial/HomogeneousElasticIsotropicDomainSH/sources.yaml
  tests/unit-tests/source/dim2/vector_sources/force_source.hpp
Labels: fix

#1157 Issue 1122 - implements 3D elastic isotropic source
  core/specfem/point/impl/field.hpp
  include/medium/compute_source.hpp
  include/medium/dim3/elastic/isotropic/source.hpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/medium/mass_matrix/dim2/acoustic.cpp
  tests/unit-tests/medium/mass_matrix/dim2/elastic_anisotropic.cpp
  tests/unit-tests/medium/mass_matrix/dim2/elastic_isotropic.cpp
  tests/unit-tests/medium/mass_matrix/dim2/poroelastic.cpp
  tests/unit-tests/medium/mass_matrix/dim3/elastic_isotropic.cpp
  tests/unit-tests/medium/mass_matrix/main.cpp
  tests/unit-tests/medium/source/dim2/acoustic.cpp
  tests/unit-tests/medium/source/dim2/elastic_anisotropic.cpp
  tests/unit-tests/medium/source/dim2/elastic_isotropic.cpp
  tests/unit-tests/medium/source/dim2/elastic_isotropic_cosserat.cpp
  tests/unit-tests/medium/source/dim2/poroelastic.cpp
  tests/unit-tests/medium/source/dim3/elastic_isotropic.cpp
  tests/unit-tests/medium/source/main.cpp
  tests/unit-tests/medium/stress/dim2/acoustic.cpp
  tests/unit-tests/medium/stress/dim2/elastic_anisotropic.cpp
  tests/unit-tests/medium/stress/dim2/elastic_isotropic.cpp
  tests/unit-tests/medium/stress/dim2/elastic_isotropic_cosserat.cpp
  tests/unit-tests/medium/stress/dim2/poroelastic_isotropic.cpp
  tests/unit-tests/medium/stress/dim3/elastic_isotropic.cpp
  tests/unit-tests/medium/stress/main.cpp
Labels: new physics

#1156 Edge-based locate point
  include/algorithms/locate_point.hpp
  include/algorithms/locate_point_impl.hpp
  src/algorithms/dim2/locate_point.cpp
  src/algorithms/dim2/locate_point_impl.cpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/assembly/locate/locate_point_on_edge.cpp
Labels: enhancement

#1179 Create edge types to sort all edges with tags
  core/specfem/assembly/coupled_interfaces/dim2/impl/interface_container.tpp
  core/specfem/assembly/edge_types/dim2/edge_types.cpp
  core/specfem/assembly/edge_types/dim2/edge_types.hpp
  core/specfem/assembly/interface_types.hpp
  core/specfem/assembly/mesh/dim2/mesh.hpp
  include/enumerations/connections.hpp
  include/enumerations/interface_definitions.hpp
  include/io/mesh/impl/fortran/dim2/read_interfaces.hpp
  include/mesh/dim2/adjacency_graph/adjacency_graph.hpp
  include/mesh/dim2/coupled_interfaces/coupled_interfaces.hpp
  include/mesh/dim2/coupled_interfaces/interface_container.hpp
  src/enumerations/connections.cpp
  src/io/mesh/impl/fortran/dim2/mesh.cpp
  src/io/mesh/impl/fortran/dim2/read_interfaces.cpp
  src/mesh/dim2/coupled_interfaces/coupled_interfaces.cpp
Labels: refactor

#1161 1092 - avoid creating empty folders in wavefield io for medium that do not exist
  include/io/HDF5/impl/dataset.hpp
  include/io/HDF5/impl/dataset.tpp
  include/io/HDF5/impl/datasetbase.hpp
  include/io/HDF5/impl/native_type.hpp
  include/io/HDF5/impl/native_type.tpp
  include/io/wavefield/reader.tpp
  include/io/wavefield/writer.tpp
Labels: enhancement

#1188 Deprecate Devel DG branch
  include/algorithms/locate_point.hpp
  include/algorithms/locate_point_impl.hpp
  pyproject.toml
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/binary_detect_N3.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/boundary.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/edges.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/model.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/dim2/model/nonconforming_interfaces.py
  scripts/gmshlayerbuilder/_gmsh2meshfem/gmsh_dep.py
  src/algorithms/dim2/locate_point.cpp
  src/algorithms/dim2/locate_point_impl.cpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/assembly/locate/locate_point_on_edge.cpp
Labels: maintenance

#1190 Fixes cmake issues with boost etc.
  CMakeLists.txt
  cmake/boost.cmake
Labels: configuration

#1189 Reimplement coupled interfaces using macros
  core/specfem/assembly/boundaries/dim2/impl/utilities.hpp
  core/specfem/assembly/coupled_interfaces/dim2/impl/interface_container.hpp
  core/specfem/assembly/coupled_interfaces/dim2/impl/interface_container.tpp
  core/specfem/assembly/coupled_interfaces2.hpp
  core/specfem/assembly/coupled_interfaces2/dim2/coupled_interface.cpp
  core/specfem/assembly/coupled_interfaces2/dim2/coupled_interface.hpp
  core/specfem/assembly/coupled_interfaces2/dim2/impl/interface_container.hpp
  core/specfem/assembly/coupled_interfaces2/dim2/impl/interface_container.tpp
  core/specfem/assembly/edge_types.hpp
  core/specfem/assembly/edge_types/dim2/edge_types.cpp
  core/specfem/assembly/interface_types.hpp
  core/specfem/data_access/check_compatibility.hpp
  core/specfem/data_access/container.hpp
  core/specfem/data_access/data_class.hpp
  core/specfem/point.hpp
  core/specfem/point/coupled_interface.hpp
  core/specfem/point/edge_index.hpp
  core/specfem/point/interface_index.hpp
  core/specfem/point/jacobian_matrix.hpp
  core/specfem/point/jacobian_matrix.tpp
  include/enumerations/coupled_interface.hpp
  include/enumerations/interface.hpp
  include/enumerations/interface_definitions.hpp
  include/execution/chunked_edge_iterator.hpp
  include/execution/chunked_intersection_iterator.hpp
  include/mesh/dim2/coupled_interfaces/interface_container.tpp
  include/policies/edge.hpp
  src/io/mesh/impl/fortran/dim2/read_interfaces.cpp
  tests/unit-tests/policies/chunked_edge.cpp
Labels: refactor

#1185 Issue 1168 - Assembly sources receivers
  core/specfem/assembly/receivers.hpp
  core/specfem/assembly/receivers/dim2/receivers.hpp
  core/specfem/assembly/receivers/dim3/receivers.hpp
  core/specfem/assembly/sources.hpp
  core/specfem/assembly/sources/dim2/sources.hpp
  core/specfem/assembly/sources/dim3/sources.hpp
  core/specfem/assembly/sources/impl/locate_sources.hpp
  core/specfem/assembly/sources/impl/source_medium.hpp
  docs/conf.py
  docs/sections/api/specfem/assembly/index.rst
  docs/sections/api/specfem/assembly/mesh/dim2/impl/utilities.rst
  docs/sections/api/specfem/assembly/receivers/common/receiver_iterator.rst
  docs/sections/api/specfem/assembly/receivers/common/receivers.rst
  docs/sections/api/specfem/assembly/receivers/dim2/index.rst
  docs/sections/api/specfem/assembly/receivers/dim3/index.rst
  docs/sections/api/specfem/assembly/receivers/index.rst
  docs/sections/api/specfem/assembly/receivers/receivers.rst
  docs/sections/api/specfem/assembly/sources/common/locate_sources.rst
  docs/sections/api/specfem/assembly/sources/common/source_medium.rst
  docs/sections/api/specfem/assembly/sources/common/sources.rst
  docs/sections/api/specfem/assembly/sources/dim2/index.rst
  docs/sections/api/specfem/assembly/sources/dim3/index.rst
  docs/sections/api/specfem/assembly/sources/index.rst
  docs/sections/api/specfem/assembly/sources/sources.rst
Labels: documentation

#1200 Updated the links in the readme and the docs
  README.md
  docs/index.rst
  docs/sections/api/specfem/point/properties/dim2/elastic_isotropic.rst
  docs/sections/cookbooks/dim2/CUBIT/index.rst
  docs/sections/developer_documentation/build_requirements.rst
  docs/sections/developer_documentation/contributing.rst
  docs/sections/developer_documentation/git_workflow.rst
Labels: documentation

#1209 1169 Part 3 - dimensionalize chunk element view and add () operator for point index
  core/specfem/chunk_element/stress_integrand.hpp
  core/specfem/data_access/accessor/chunk_element.hpp
  include/datatypes/chunk_element_view.hpp
  include/kokkos_kernels/impl/compute_seismogram.tpp
Labels: ignore-for-release

#1186 Compute Reparameterization for Nonconforming Interfaces
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection.cpp
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection.hpp
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection_in_assembly.cpp
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection_in_assembly.hpp
  core/specfem/point/coordinates.hpp
  core/specfem/point/coordinates.tpp
  include/algorithms/locate_point.hpp
  src/algorithms/dim2/locate_point.cpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/nonconforming/reparameterizations/compute_intersection_test.cpp
  tests/unit-tests/nonconforming/runner.cpp
Labels: dependency, new physics

#1210 1169 Part 4 - add index operators to chunk element view types
  core/specfem/assembly/compute_source_array/dim2/compute_source_array.tpp
  core/specfem/assembly/compute_source_array/dim3/compute_source_array.tpp
  core/specfem/point/coordinates.hpp
  core/specfem/point/impl/field.hpp
  include/datatypes/chunk_element_view.hpp
  include/datatypes/impl/chunk_element_subview.hpp
  include/datatypes/point_view.hpp
  include/execution/chunked_domain_iterator.hpp
  include/kokkos_kernels/impl/compute_mass_matrix.tpp
  include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
  include/medium/compute_cosserat_couple_stress.hpp
Labels: ignore-for-release

#1217 Issue 824 - Nightly benchmarks snakemake workflows
  benchmarks/src/CMakeFiles/nightly_benchmarks.smk.in
  benchmarks/src/CMakeFiles/nightly_config.yaml.in
  benchmarks/src/CMakeLists.txt
  benchmarks/src/dim2/fluid-solid-interface/CMakeFiles/Snakefile.in
  benchmarks/src/dim2/homogeneous-medium-flat-topography/CMakeFiles/Snakefile.in
  benchmarks/src/nightly_benchmarks/cli.py
  benchmarks/src/nightly_benchmarks/io_utils.py
  benchmarks/src/nightly_benchmarks/kp_parser.py
  benchmarks/src/run_parser.py
  include/kokkos_kernels/impl/compute_seismogram.tpp
  include/kokkos_kernels/impl/compute_source_interaction.tpp
  include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
  include/kokkos_kernels/impl/divide_mass_matrix.tpp
  include/timescheme/newmark.tpp
  pyproject.toml
  uv.lock
Labels: maintenance

#1221 Added post step to nightly snakemake
  benchmarks/src/CMakeFiles/nightly_benchmarks.smk.in
Labels: ignore-for-release

#1227 Mortar Transfer Function
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection.cpp
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection.hpp
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection_in_assembly.cpp
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection_in_assembly.hpp
  core/specfem/assembly/nonconforming_interfaces/dim2/impl/compute_intersection_in_assembly.tpp
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/nonconforming/reparameterizations/set_transfer_functions_test.cpp
Labels: new physics

#1223 1170 Part 2 - 3D specialization for chunk_elements
  include/algorithms/divergence.hpp
  include/algorithms/gradient.hpp
  include/datatypes/chunk_element_view.hpp
  include/datatypes/impl/chunk_element_subview.hpp
Labels: ignore-for-release
